version: '2'
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: exampleshop
      POSTGRES_USER: exampleshop
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
  app:
    image: example-shop-py
    environment:
      SECRET_KEY: my_secret
      DATABASE_URI: postgresql+psycopg2://exampleshop:exampleshop@db/exampleshop
      APP_SETTINGS: app.config.ProductionConfig
    ports:
      - "5000:80"
    depends_on:
      - "db"
