version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.6-stretch
        environment:
          APP_SETTINGS: project.config.TestingConfig
          TEST_DATABASE_URL: postgresql+psycopg2://circleci@localhost/db_test
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: db_test
    working_directory: ~/repo
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirements.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-
      - run:
          name: install dependencies
          command: |
            python3 -m venv civenv
            . ./civenv/bin/activate
            pip install -r requirements.txt
      - save_cache:
          paths:
            - ./civenv
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: run tests
          command: |
            . ./civenv/bin/activate
            mkdir test-reports
            pytest --junitxml=test-reports/junit.xml
      - store_test_results:
          path: test-reports
      - store_artifacts:
          path: test-reports    
